[profile.default]
src = "smart-contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = 'test/foundry'

remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
